---
title: "Capstone Project Proposal"
author: "Vishnu Reddy"
date: "November 11, 2017"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

## Background 

The dataset contains historical product demand for a manufacturing company with footprints globally. The company provides thousands of products within 33 product categories. There are four central warehouses to ship products within the region it is responsible for. Since the products are manufactured in different locations all over the world, it normally takes more than one month to ship products via sea to different central warehouses. 


## Goals

1. Accurately forecast the demand for each product for the remaining         months of 2017.
2. Accurately forecast the demand for each product category for the          remaining months of 2017. 
3. To identify, analyze and report trends within each warehouse and          product category.

## Data

The dataset provides information on past demand (Jan 2011 - Jan 2017) for the 33 product categories and 2172 products. The data set was obtained from [Kaggle](https://www.kaggle.com/felixzhao/productdemandforecasting).

## Approach

I plan to use multiple linear regression analysis for my forecast and I plan on comparing the forecast obtained with other timeseries forecasting techniques (eg. ARIMA).

## Deliverables

1. Report
2. Source Code
3. Slide Deck
